### ISSUE TITLE
undefined C function `InitAudioDevice`

### ISSUE THREAD

**Issue by acklavidian** [MajorHard/vraylib#5]
I installed vraylib via:
```
v install damienfamed75.vraylib
```

When I use the lib I keep getting this error on OSX and Linux:
```
./audio.v:43:1: undefined C function `InitAudioDevice`
define it with `fn C.InitAudioDevice([args]) [return_type]`                                           
   41| pub fn init_audio_device() {
   42|  C.InitAudioDevice()
   43| }
       ^
   44| 
   45| // Close the audio device and context (and music stream)
```

**Comment by acklavidian** [comment]
Oh I forgot to mention that is only after I rename the module to get around this error:
```
cannot import module "MajorHard.vraylib" (not found)
    1| module main
    2| 
    3| import MajorHard.vraylib
                      ^
    4| 
    5| const (
```
I am a new to Vlang, and this is my first experience with VPM so its very possible I am missing something obvious.

**Comment by JustinRyanH** [comment]
@acklavidian Did the merged in issue fix this?

**Comment by acklavidian** [comment]
@JustinRyanH  yes. I was able to run some of the examples. Thank you very much!
